paths:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  text_index: "data/index/text.faiss"
  text_ids:   "data/index/text_ids.jsonl"
  bm25_index: "data/index/bm25.pkl"
  reranker:   "cross-encoder/ms-marco-MiniLM-L-6-v2"
  text_embedder: "sentence-transformers/all-MiniLM-L6-v2"
  gguf_path: "models/gguf/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"

chunking:
  size: 600
  overlap: 80

retrieval:
  k_dense: 50
  k_bm25: 50
  k_fused: 40
  dense_weight: 0.65
  bm25_weight: 0.35

rerank:
  top_k: 6

generation:
  max_new_tokens: 256
  temperature: 0.4
  top_p: 0.9
  context_window: 4096
  kv_cache: true